project:
  type: website
  output-dir: docs

website:
  title: "Aaron Olson"
  image: "websitePreview.jpeg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - blogposts.qmd
  page-footer: 
   background: dark
   left: Â© 2024 Aaron Olson
   right:
    - icon: twitter
      href: https://twitter.com/marginofaaron
    - icon: github
      href: https://github.com/marginofaaron
    - icon: envelope-at
      href: mailto:aaroneolson@protonmail.com
  favicon: bar-chart-emoji.ico
  twitter-card:
    creator: "@marginofaaron"
  open-graph: true
  site-url: https://aaroneolson.me
  back-to-top-navigation: true
   
format:
  html:
    theme: 
      - sandstone
      - styles.scss
    toc: true
    df-print: paged

editor: source

